# 开发环境配置文件
spring:
  application:
    name: user-serve-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.128.128:8848

server:
  port: 11000
  servlet:
    context-path: /user-provider